# name نام پکیج قرار می گیرد که قرار است در  گیت آن را فراخوانی کنیم
name: number
publish_to: none

# add sdk  support on android
environment:
  sdk: '>=2.18.1 <3.0.0'


#  for add  package class other of pub dev
dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.0


# for add ui to liberary 
dependencies:
  flutter:
    sdk: flutter  