# name نام پکیج قرار می گیرد که قرار است در  گیت آن را فراخوانی کنیم
name: number
description: "این یک پکیج تست  برای  ارسال به پاب دو می باشد"
version:  1.0.1+1
repository: https://github.com/ismaelmazrooei/test.git


# add sdk  support on android
environment:
  sdk: '>=2.18.1 <3.0.0'


#  for add  package class other of pub dev
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


# for add ui to liberary 
dependencies:
  flutter:
    sdk: flutter  